baseURL: https://pehei.de

title: Peter Heisig
author:
  name: Peter Heisig

defaultContentLanguage: de
theme: hello-friend

PygmentsCodeFences: true
PygmentsStyle: monokai
rssLimit: 10

copyright: This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.

archetypeDir: archetypes
contentDir: content
dataDir: data
layoutDir: layouts
publishDir: public

# disqusShortname: pehei
googleAnalytics: UA-3690899-5

buildDrafts: false
buildFuture: false
buildExpored: false
canonifyURLs: true

enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true
enableMissingTranslationPlaceholders: true

disableRSS: false
disableSitemap: false
disable404: false
disableHugoGeneratorInject: false

permalinks:
  posts: posts/:title/

blackfriday:
  hrefTargetBlank: true

privacy:
  disqus:
    disable: true

  googleAnalytics:
    disable: false
    anonymizeIP: true
    respectDoNotTrack: true

params:
  gitUrl: https://github.com/phdd/phdd.github.io/commit/

  dateform: 02.01.2006
  dateformShort: 02.01.
  dateformNum: 02.01.2006
  dateformNumTime: 02.01.2006
  
  images:
    - /img/peter-heisig-quad.jpg
  
  customJS: 
    - /cookieconsent.js

  customCSS:
    - /flag-icon.css
    - /cookieconsent.css
    - /custom.css
  
  justifyContent: true
  defaultTheme: dark
  themeColor: #252627

  logo:
    logoText: $ cd /home/peter

  social:
    - name: github
      url: https://github.com/phdd
    - name: xing
      url: https://www.xing.com/profile/Peter_Heisig4
    - name: keybase
      url: https://keybase.io/phdd
    - name: email
      url: mailto:kontakt@pehei.de

languages:
  de:
    weight: 1
    homeSubtitle: Softwareingenieur
    languageName: Deutsche
    contentDir: content/de
    description: Software-Beratung und -Entwicklung aus Dresden
    keywords:
      - ""

    menu:
      main:
        - identifier: posts
          name: Posts
          url: posts/
          weight: 10
        #- identifier: about
        #  name: über mich
        #  url: über-mich/
        #  weight: 20

      footer:
        - identifier: imprint
          name: Impressum
          url: impressum/
          weight: 10
        - identifier: privacy-policy
          name: Datenschutz
          url: datenschutz/
          weight: 20

  en:
    weight: 2
    homeSubtitle: Software Engineer
    languageName: English
    contentDir: content/en
    description: Software consulting and engineering from Dresden
    keywords:
      - ""

    menu:
      main:
        - identifier: posts
          name: Posts
          url: posts/
          weight: 10
        #- identifier: about
        #  name: about me
        #  url: about-me/
        #  weight: 20

      footer:
        - identifier: imprint
          name: Imprint
          url: imprint/
          weight: 10
        - identifier: privacy-policy
          name: Privacy Policy
          url: privacy-policy/
          weight: 20
